export const realWork = [
  {
    slug: "lp-sealcoating",
    name: "LP Sealcoating",
    category: "Websites",
    industry: "Sealcoating, crack filling, striping, paving",
    location: "Peabody, MA",
    url: "https://lpsealcoatingdemo.lovable.app",
    color: "#8b9cf6",
  },
  {
    slug: "alameda-landscaping",
    name: "Alameda Landscaping",
    category: "Websites",
    industry: "Landscaping, tree care, hardscape",
    location: "Port Orchard, WA",
    url: "https://alamedalandscapingdemo.lovable.app",
    color: "#8b9cf6",
  },
  {
    slug: "made-by-la",
    name: "Made by L.A.",
    category: "E-Commerce",
    industry: "Handcrafted decor, personalized gifts",
    location: "USA",
    url: "https://madebyla-showcase.lovable.app",
    color: "#8b9cf6",
  },
  {
    slug: "masterpiece-hfs",
    name: "Masterpiece HFS",
    category: "Websites",
    industry: "Construction, lawn, power washing, hauling",
    location: "Stillwater, OK",
    url: "https://masterpiecehfs.vercel.app",
    color: "#8b9cf6",
  },
  {
    slug: "js-barber-shop",
    name: "J's Barber Shop",
    category: "Websites",
    industry: "Barbershop, haircuts, beard grooming",
    location: "Dracut, MA",
    url: "https://jsbarbershop.lovable.app",
    color: "#8b9cf6",
  },
  {
    slug: "shay-crawford",
    name: "Shay Crawford Realty",
    category: "Websites",
    industry: "Real estate, luxury property, Keller Williams",
    location: "Houston, TX",
    url: "https://ari-builds.github.io/shay-crawford/",
    color: "#c5a059",
  },
]
