export const services = [
  {
    slug: "svc-web-design",
    title: "Web Design",
    tagline: "Pixel-perfect interfaces that captivate and convert.",
    description: "We craft visually stunning, user-centered designs that communicate your brand identity and guide visitors seamlessly toward conversion. Every layout, color palette, and typographic choice is intentional.",
    color: "#6366f1",
    gradient: "from-indigo-500 to-purple-600",
    iconName: "palette",
    features: [
      { title: "Custom UI/UX Design", desc: "Tailored wireframes and high-fidelity mockups built around your brand guidelines and user research." },
      { title: "Responsive Layouts", desc: "Fluid designs that look impeccable across every screen size — from mobile to ultrawide." },
      { title: "Design Systems", desc: "Component libraries and style guides ensuring visual consistency across your entire digital ecosystem." },
      { title: "Interactive Prototypes", desc: "Clickable Figma prototypes for user testing and stakeholder buy-in before a single line of code is written." },
      { title: "Accessibility First", desc: "WCAG 2.1 AA compliant designs with semantic structure, contrast ratios, and keyboard navigation built in." },
    ],
    stats: [
      { label: "Projects Delivered", value: "340+" },
      { label: "Avg. Satisfaction", value: "4.9/5" },
      { label: "Conversion Lift", value: "64%" },
      { label: "Awards Won", value: "12" },
    ],
    testimonials: [
      { name: "Olivia Hart", role: "CEO, Lumina Studios", text: "Our new site doubled online inquiries within the first month. The design team understood our vision better than we did." },
      { name: "James Moreau", role: "Founder, Crestwood Co.", text: "The attention to detail is extraordinary. Every micro-interaction feels purposeful and polished." },
    ],
  },
  {
    slug: "svc-web-dev",
    title: "Web Development",
    tagline: "Robust, scalable websites engineered for performance.",
    description: "From static landing pages to full-stack web applications, we build with modern frameworks and best-in-class architecture. Clean code, fast load times, and future-proof scalability.",
    color: "#3b82f6",
    gradient: "from-blue-500 to-cyan-600",
    iconName: "code",
    features: [
      { title: "Frontend Engineering", desc: "React, Next.js, and Vue applications with optimized bundles, SSR, and dynamic routing for blazing-fast experiences." },
      { title: "Backend Architecture", desc: "Node.js, Python, and Go services with RESTful and GraphQL APIs designed for reliability and throughput." },
      { title: "CMS Integration", desc: "Headless CMS solutions — Sanity, Strapi, Contentful — giving your team full control over content without touching code." },
      { title: "E-Commerce Engines", desc: "Shopify, Medusa, or custom checkout flows engineered for conversion and inventory management at scale." },
      { title: "DevOps & Hosting", desc: "CI/CD pipelines, Vercel/AWS deployment, monitoring, and automated rollbacks for worry-free releases." },
    ],
    stats: [
      { label: "Apps Built", value: "280+" },
      { label: "Avg. Load Time", value: "0.8s" },
      { label: "Uptime SLA", value: "99.97%" },
      { label: "Technologies", value: "24+" },
    ],
    testimonials: [
      { name: "David Okonkwo", role: "CTO, Finlytics", text: "They rebuilt our entire platform in 12 weeks — something our previous agency couldn't do in a year. Exceptional engineering." },
      { name: "Mei-Lin Chang", role: "Product Lead, Kōsha", text: "The code quality is outstanding. We inherited a clean, well-documented codebase that our internal team could extend immediately." },
    ],
  },
  {
    slug: "svc-ecommerce",
    title: "E-Commerce",
    tagline: "Online stores that drive revenue, not just traffic.",
    description: "Full-funnel e-commerce solutions designed to maximize average order value, reduce cart abandonment, and create memorable shopping experiences that keep customers coming back.",
    color: "#10b981",
    gradient: "from-emerald-500 to-teal-600",
    iconName: "shoppingCart",
    features: [
      { title: "Storefront Design", desc: "Conversion-optimized product pages, intuitive navigation, and streamlined checkout flows that feel effortless." },
      { title: "Payment & Shipping", desc: "Multi-gateway payment processing, real-time shipping calculations, and automated tax compliance out of the box." },
      { title: "Inventory Management", desc: "Real-time stock tracking, supplier integrations, and low-stock alerts that prevent overselling." },
      { title: "Marketing Integrations", desc: "Email flows, abandoned cart recovery, upsells, and loyalty programs wired directly into your store." },
      { title: "Analytics & Reporting", desc: "Custom dashboards tracking LTV, CAC, ROAS, and cohort analysis to inform every business decision." },
    ],
    stats: [
      { label: "Stores Launched", value: "160+" },
      { label: "GMV Processed", value: "$42M+" },
      { label: "Avg. ROAS", value: "5.2x" },
      { label: "Cart Recovery", value: "18.3%" },
    ],
    testimonials: [
      { name: "Sofia Reyes", role: "Owner, Mila & Co.", text: "Revenue grew 340% in six months. The abandoned cart flows alone recovered over $40K in lost sales." },
      { name: "Liam O'Connell", role: "CEO, Urban Provisions", text: "They built a multi-brand storefront that handles 50K SKUs without breaking a sweat. Rock-solid platform." },
    ],
  },
  {
    slug: "svc-seo",
    title: "SEO Optimization",
    tagline: "Dominate search. Drive organic growth.",
    description: "Data-driven SEO strategies that improve rankings, increase organic traffic, and generate qualified leads. Technical audits, content strategy, and ongoing optimization included.",
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-600",
    iconName: "search",
    features: [
      { title: "Technical SEO Audit", desc: "Comprehensive crawl analysis, Core Web Vitals assessment, and structured data implementation for maximum indexability." },
      { title: "Keyword Strategy", desc: "Competitive keyword mapping, search intent analysis, and topic clusters that capture high-intent traffic at every funnel stage." },
      { title: "On-Page Optimization", desc: "Meta tags, header structure, internal linking, and content optimization aligned with Google's E-E-A-T guidelines." },
      { title: "Local SEO", desc: "Google Business Profile optimization, local citation building, and review management for multi-location businesses." },
      { title: "Link Building", desc: "White-hat outreach campaigns, digital PR, and strategic partnerships that earn high-authority backlinks." },
    ],
    stats: [
      { label: "Rankings Improved", value: "1.2K+" },
      { label: "Avg. Traffic Lift", value: "187%" },
      { label: "Clients Served", value: "90+" },
      { label: "Avg. Position", value: "#3.2" },
    ],
    testimonials: [
      { name: "Raj Patel", role: "Marketing Director, Zestful", text: "Within 90 days we hit page one for our top 15 keyword targets. The ROI has been phenomenal." },
      { name: "Claire Dubois", role: "Founder, Maison Luxe", text: "Our organic traffic tripled in six months. The technical audit uncovered issues we didn't know were costing us rankings." },
    ],
  },
  {
    slug: "svc-responsive",
    title: "Responsive Design",
    tagline: "Flawless experiences on every device.",
    description: "Responsive design engineering that ensures your digital presence adapts beautifully to any screen. Mobile-first approach with obsessive attention to touch targets, readability, and performance.",
    color: "#8b5cf6",
    gradient: "from-violet-500 to-purple-600",
    iconName: "monitor",
    features: [
      { title: "Mobile-First Framework", desc: "Touch-optimized interfaces with thumb-friendly navigation, responsive typography, and adaptive image loading." },
      { title: "Cross-Browser Testing", desc: "Rigorous testing across Chrome, Safari, Firefox, Edge, and mobile browsers — no edge case left unchecked." },
      { title: "Adaptive Layouts", desc: "CSS Grid and Flexbox architectures that reflow content intelligently from watch faces to 4K displays." },
      { title: "Performance Budgets", desc: "Strict performance budgets ensuring sub-2-second load times on 3G connections across all device classes." },
      { title: "Accessibility Parity", desc: "Identical functionality and information access across devices, with screen reader and voice navigation support." },
    ],
    stats: [
      { label: "Devices Covered", value: "2.4K+" },
      { label: "Mobile Bounce Rate", value: "-52%" },
      { label: "Pages Optimized", value: "1.8K+" },
      { label: "Avg. Lighthouse", value: "96" },
    ],
    testimonials: [
      { name: "Anika Sharma", role: "UX Director, Dotvibe", text: "Our mobile conversion rate jumped 73% after the responsive redesign. The attention to touch interactions is incredible." },
      { name: "Tom Keller", role: "VP Product, Streamline", text: "They made our complex dashboard usable on a phone. That's not easy, and they nailed it." },
    ],
  },
  {
    slug: "svc-performance",
    title: "Performance",
    tagline: "Speed is a feature. We make it yours.",
    description: "Performance optimization that transforms sluggish sites into lightning-fast experiences. Core Web Vitals, image optimization, caching strategies, and CDN configuration for instant loading.",
    color: "#ef4444",
    gradient: "from-red-500 to-rose-600",
    iconName: "zap",
    features: [
      { title: "Core Web Vitals", desc: "LCP, FID, and CLS optimization targeting Google's top thresholds for search ranking boost and user retention." },
      { title: "Image & Asset Optimization", desc: "Next-gen formats, responsive image sets, lazy loading, and compression pipelines that cut payloads by 70%+" },
      { title: "CDN & Edge Caching", desc: "Global CDN deployment with edge caching, Brotli compression, and HTTP/3 for sub-100ms TTFB worldwide." },
      { title: "Code Splitting", desc: "Tree-shaking, dynamic imports, and granular code splitting that ensure users only download what they need." },
      { title: "Database Query Tuning", desc: "Index optimization, query profiling, and connection pooling that reduce database response times by 90%+" },
    ],
    stats: [
      { label: "Avg. Speed Gain", value: "3.4x" },
      { label: "Data Saved", value: "18TB/mo" },
      { label: "Pages Optimized", value: "950+" },
      { label: "LCP Improved", value: "82%" },
    ],
    testimonials: [
      { name: "Erik Johansson", role: "CTO, Nordpeak", text: "They reduced our page load time from 6.2s to 1.1s. Our bounce rate dropped 40% and revenue climbed 22%." },
      { name: "Naomi Wanjiku", role: "Engineering Lead, Sendy", text: "The performance audit was incredibly thorough. Every recommendation was backed by data and prioritized by impact." },
    ],
  },
  {
    slug: "svc-leadgen",
    title: "Lead Generation",
    tagline: "Turn visitors into qualified opportunities.",
    description: "Strategic lead generation systems combining high-converting landing pages, smart form automation, and multi-channel capture funnels that fill your pipeline with decision-ready prospects.",
    color: "#06b6d4",
    gradient: "from-cyan-500 to-blue-600",
    iconName: "target",
    features: [
      { title: "Conversion Landing Pages", desc: "A/B tested page architectures with persuasive copy, social proof, and scarcity triggers that maximize conversion rates." },
      { title: "Smart Form Automation", desc: "Conditional logic forms, progressive profiling, and auto-enrichment that capture more data without friction." },
      { title: "Multi-Channel Capture", desc: "Chat widgets, exit-intent popups, email capture, and SMS opt-ins coordinated across your entire digital presence." },
      { title: "CRM Integration", desc: "Real-time lead sync to Salesforce, HubSpot, or custom CRM with lead scoring and automated follow-up sequences." },
      { title: "Analytics & Attribution", desc: "Source-level attribution, funnel drop-off analysis, and cohort reporting to optimize CAC and LTV." },
    ],
    stats: [
      { label: "Leads Generated", value: "340K+" },
      { label: "Avg. Conv. Rate", value: "8.7%" },
      { label: "Clients Active", value: "110+" },
      { label: "CAC Reduction", value: "43%" },
    ],
    testimonials: [
      { name: "Brett Holloway", role: "VP Sales, ProCore", text: "Our cost per lead dropped from $87 to $34. The automated follow-up sequences alone are worth the investment." },
      { name: "Yuki Tanaka", role: "Growth Lead, Atelier", text: "They built a lead engine that generates 200+ qualified opportunities monthly — on autopilot." },
    ],
  },
  {
    slug: "svc-outreach",
    title: "AI Outreach Campaigns",
    tagline: "Personalized at scale. Intelligent by design.",
    description: "AI-powered outreach campaigns that craft hyper-personalized email sequences, LinkedIn messages, and SMS campaigns. Natural language generation tailored to each prospect's profile and behavior.",
    color: "#f97316",
    gradient: "from-orange-500 to-red-600",
    iconName: "send",
    features: [
      { title: "AI Personalization Engine", desc: "Dynamic content insertion using prospect data — job title, industry, recent news — for messages that feel handwritten." },
      { title: "Omnichannel Sequences", desc: "Coordinated email, LinkedIn, and SMS cadences with intelligent channel switching based on engagement patterns." },
      { title: "A/B Testing Automation", desc: "Automated subject line, body copy, and send-time testing that converges on winning variants without manual intervention." },
      { title: "Reply Detection & Routing", desc: "NLP-powered reply analysis that auto-tags intent and routes hot leads to sales instantly." },
      { title: "Performance Analytics", desc: "Real-time dashboards tracking open rates, reply rates, meeting booked, and pipeline generated — per campaign and per rep." },
    ],
    stats: [
      { label: "Emails Sent", value: "4.2M+" },
      { label: "Avg. Reply Rate", value: "14.6%" },
      { label: "Meetings Booked", value: "12K+" },
      { label: "Pipeline Generated", value: "$18M+" },
    ],
    testimonials: [
      { name: "Alexandra Russo", role: "Head of Sales, Velos", text: "The AI-generated sequences outperform our best manual emails by 40%. This is the future of outbound." },
      { name: "Carlos Mendez", role: "CEO, NexaGrowth", text: "Campaign setup that used to take two weeks now takes two hours. The personalization is uncanny." },
    ],
  },
  {
    slug: "svc-ai-auto",
    title: "AI Automation",
    tagline: "Workflows that run themselves.",
    description: "Custom AI automation solutions that eliminate repetitive tasks, streamline operations, and free your team to focus on high-impact work. From document processing to decision automation.",
    color: "#a855f7",
    gradient: "from-purple-500 to-pink-600",
    iconName: "bot",
    features: [
      { title: "Intelligent Document Processing", desc: "AI that extracts, classifies, and validates data from invoices, contracts, and forms with 99.2% accuracy." },
      { title: "Workflow Automation", desc: "Visual workflow builders connecting your tools — Slack, email, CRM, databases — into automated sequences." },
      { title: "Decision Automation", desc: "Rule-based and ML-powered decision engines that approve, flag, or route items without human touch." },
      { title: "Data Extraction & Enrichment", desc: "Automated scraping, parsing, and enrichment pipelines that keep your data fresh and actionable." },
      { title: "Custom AI Agents", desc: "Task-specific AI agents trained on your processes, documentation, and data for autonomous task completion." },
    ],
    stats: [
      { label: "Hours Saved/Month", value: "1.4K+" },
      { label: "Processes Automated", value: "320+" },
      { label: "Accuracy Rate", value: "99.2%" },
      { label: "ROI Average", value: "8.6x" },
    ],
    testimonials: [
      { name: "Diane Chen", role: "COO, MedLogix", text: "We automated 80% of our claims processing. What used to take five full-time employees now runs with minimal oversight." },
      { name: "Ryan O'Neil", role: "Operations Director, ShipFast", text: "The invoice processing automation saved us $240K annually. Implementation was smooth and the team was incredibly responsive." },
    ],
  },
  {
    slug: "svc-social",
    title: "Social Media Autopilot",
    tagline: "Consistent presence. Zero daily effort.",
    description: "AI-driven social media management that plans, creates, schedules, and analyzes content across all major platforms. Calendar management, visual generation, and engagement analytics on autopilot.",
    color: "#ec4899",
    gradient: "from-pink-500 to-rose-600",
    iconName: "share2",
    features: [
      { title: "AI Content Generation", desc: "Platform-optimized posts, captions, and visuals generated from your brand voice and content strategy brief." },
      { title: "Smart Scheduling", desc: "Optimal posting times calculated per platform and audience. Auto-schedules your monthly calendar in minutes." },
      { title: "Cross-Platform Publishing", desc: "Simultaneous or staggered publishing to Instagram, LinkedIn, Twitter/X, Facebook, TikTok, and Threads." },
      { title: "Engagement Analytics", desc: "Real-time metrics on reach, engagement rate, follower growth, and sentiment — with actionable recommendations." },
      { title: "Content Remixing", desc: "Automatically repurpose high-performing content into different formats — video to carousel, blog to thread, etc." },
    ],
    stats: [
      { label: "Accounts Managed", value: "430+" },
      { label: "Avg. Engagement", value: "4.8x" },
      { label: "Posts Published", value: "28K+" },
      { label: "Followers Gained", value: "1.2M+" },
    ],
    testimonials: [
      { name: "Maya Goldstein", role: "Brand Director, Wilder", text: "We maintain six platforms consistently without a dedicated social media manager. The AI-generated content is on-brand and performs." },
      { name: "Jake Patterson", role: "Founder, Outbound Co.", text: "Our engagement rate quadrupled. The scheduling and analytics alone save us 20+ hours a week." },
    ],
  },
  {
    slug: "svc-voice",
    title: "AI Voice Agent",
    tagline: "Human-like conversations. 24/7 availability.",
    description: "Conversational AI voice agents that handle inbound calls, qualify leads, book appointments, and answer FAQs with natural speech that customers can't distinguish from human representatives.",
    color: "#14b8a6",
    gradient: "from-teal-500 to-emerald-600",
    iconName: "phone",
    features: [
      { title: "Natural Conversation Flow", desc: "Neural voice models with context awareness, interruption handling, and emotional tone adaptation for fluid conversations." },
      { title: "Lead Qualification", desc: "Structured discovery calls that capture intent, budget, timeline, and authority — with CRM update on hang-up." },
      { title: "Appointment Booking", desc: "Calendar integration for real-time availability, booking, rescheduling, and confirmation with SMS reminders." },
      { title: "Multi-Language Support", desc: "Real-time language detection and switching across English, Spanish, French, German, and Mandarin with native accent fidelity." },
      { title: "Call Analytics", desc: "Transcripts, sentiment analysis, objection tracking, and call scoring with coaching recommendations for human agents." },
    ],
    stats: [
      { label: "Calls Handled", value: "180K+" },
      { label: "Avg. Satisfaction", value: "4.7/5" },
      { label: "Hours Saved/Week", value: "340+" },
      { label: "Booking Rate", value: "62%" },
    ],
    testimonials: [
      { name: "Lisa Park", role: "Practice Manager, DentalCare", text: "Patients can't tell they're talking to AI. Our front desk team went from overwhelmed to fully focused on patient care." },
      { name: "Mike Torres", role: "Owner, Torres Plumbing", text: "We never miss a call now — even at 2 AM. The voice agent books appointments and we just show up." },
    ],
  },
  {
    slug: "svc-workflows",
    title: "Business Automation Workflows",
    tagline: "Connect your tools. Multiply your output.",
    description: "End-to-end business process automation that connects your entire tech stack. Custom workflows that trigger actions across CRM, email, billing, project management, and internal tools seamlessly.",
    color: "#6366f1",
    gradient: "from-indigo-500 to-violet-600",
    iconName: "gitBranch",
    features: [
      { title: "Cross-Tool Orchestration", desc: "Connect 200+ tools — Salesforce, HubSpot, Slack, Asana, QuickBooks — into coordinated, event-driven workflows." },
      { title: "Lead-to-Cash Automation", desc: "Automated pipelines from lead capture through quoting, invoicing, and payment collection with approval gates." },
      { title: "Employee Onboarding", desc: "Trigger-based sequences that provision accounts, assign training, and schedule check-ins across your HR stack." },
      { title: "Approval Routing", desc: "Smart conditional approval chains that escalate based on amount, department, or compliance requirements." },
      { title: "Audit & Compliance Logging", desc: "Immutable audit trails, SOC 2 compliant logging, and automated report generation for every workflow execution." },
    ],
    stats: [
      { label: "Workflows Active", value: "540+" },
      { label: "Integrations Built", value: "180+" },
      { label: "Avg. Time Saved", value: "22h/wk" },
      { label: "Error Reduction", value: "96%" },
    ],
    testimonials: [
      { name: "Sarah Mitchell", role: "COO, CloudPeak", text: "We connected 14 different tools into automated workflows. Month-end close went from 5 days to 4 hours." },
      { name: "Daniel Kariuki", role: "IT Director, Grant Thornton", text: "The approval workflow automation eliminated our biggest bottleneck. Decisions that took days now happen in minutes." },
    ],
  },
  {
    slug: "svc-content",
    title: "Content Vault & Management",
    tagline: "Your content. Organized. Accessible. Automated.",
    description: "Centralized content management platform with AI-powered organization, version control, approval workflows, and multi-channel publishing. Your entire content operation in one place.",
    color: "#d946ef",
    gradient: "from-fuchsia-500 to-pink-600",
    iconName: "fileText",
    features: [
      { title: "Central Content Hub", desc: "Unified repository for all your content — docs, images, video, audio — with full-text search and smart tagging." },
      { title: "AI Content Organization", desc: "Auto-tagging, topic clustering, and content gap analysis that surfaces what to create next." },
      { title: "Approval Workflows", desc: "Custom review chains with Slack notifications, inline commenting, and version comparison for seamless collaboration." },
      { title: "Multi-Channel Publishing", desc: "One-click publishing to web, social, email, and print — with platform-specific formatting applied automatically." },
      { title: "Content Analytics", desc: "Performance tracking per piece, author, channel, and topic — with recommendations for content refresh and optimization." },
    ],
    stats: [
      { label: "Assets Stored", value: "620K+" },
      { label: "Content Velocity", value: "3.4x" },
      { label: "Teams Using It", value: "85+" },
      { label: "Publish Efficiency", value: "71%" },
    ],
    testimonials: [
      { name: "Emma Whitfield", role: "Content Director, Voyager Media", text: "We went from chaos to a streamlined content engine. The AI tagging alone saves our team 15 hours a week." },
      { name: "Chris Nakamura", role: "Head of Marketing, Blueprint", text: "Content approval used to be the bottleneck. Now campaigns go from draft to live in 48 hours instead of two weeks." },
    ],
  },
  {
    slug: "svc-analytics",
    title: "Analytics Dashboards",
    tagline: "Data visualizations that drive decisions.",
    description: "Custom analytics dashboards that aggregate data from every corner of your business. Real-time KPIs, cohort analysis, forecasting, and drill-downs that turn raw data into actionable intelligence.",
    color: "#0ea5e9",
    gradient: "from-sky-500 to-blue-600",
    iconName: "barChart3",
    features: [
      { title: "Custom Dashboard Builder", desc: "Drag-and-drop interface for building role-specific dashboards with charts, tables, and KPIs from any data source." },
      { title: "Real-Time Data Pipelines", desc: "Streaming data ingestion from APIs, databases, and webhooks with sub-second refresh for live operational visibility." },
      { title: "AI-Powered Forecasting", desc: "Machine learning models that predict revenue, churn, demand, and capacity with confidence intervals and scenario modeling." },
      { title: "Automated Reporting", desc: "Scheduled PDF/CSV reports delivered to Slack, email, or your data warehouse — no manual export needed." },
      { title: "Embedded Analytics", desc: "White-label dashboards you can embed into your product for customer-facing reporting and insights." },
    ],
    stats: [
      { label: "Dashboards Built", value: "260+" },
      { label: "Data Sources", value: "190+" },
      { label: "Daily Queries", value: "2.1M+" },
      { label: "Avg. Time Saved", value: "18h/wk" },
    ],
    testimonials: [
      { name: "Andrew Kim", role: "Head of Data, Stacks", text: "We consolidated 8 separate reporting tools into one dashboard. The forecasting model predicted Q4 revenue within 2%." },
      { name: "Fatima Al-Rashid", role: "VP Analytics, Quantum", text: "The embedded analytics let us ship customer-facing reports in weeks instead of quarters. Our clients love it." },
    ],
  },
  {
    slug: "svc-maintenance",
    title: "Website Maintenance & Support",
    tagline: "Your site stays fresh. You stay focused.",
    description: "Ongoing website maintenance and support that keeps your digital presence secure, up-to-date, and performing at its peak. From security patches to content updates, we handle it all.",
    color: "#84cc16",
    gradient: "from-lime-500 to-green-600",
    iconName: "wrench",
    features: [
      { title: "Security Monitoring", desc: "24/7 threat detection, malware scanning, firewall management, and immediate patching for vulnerabilities." },
      { title: "Regular Content Updates", desc: "Text changes, image swaps, blog posts, and page additions — submit a request and we deploy within 24 hours." },
      { title: "Performance Optimization", desc: "Monthly speed audits, database optimization, and cache tuning to ensure your site stays fast as it grows." },
      { title: "Backup & Recovery", desc: "Automated daily backups with point-in-time recovery and disaster recovery testing every quarter." },
      { title: "Quarterly Feature Enhancements", desc: "Small feature drops every quarter — new sections, integrations, or functionality improvements included in your plan." },
    ],
    stats: [
      { label: "Sites Maintained", value: "310+" },
      { label: "Avg. Response Time", value: "14min" },
      { label: "Security Incidents", value: "0" },
      { label: "Updates Deployed", value: "6.8K+" },
    ],
    testimonials: [
      { name: "Nina Petrova", role: "Marketing Ops, Stellara", text: "Having a dedicated maintenance team gives us peace of mind. We haven't worried about our site in two years." },
      { name: "Tommy Chen", role: "Director, Pacific Dental", text: "Their 24-hour turnaround on content updates keeps our site current without distracting our team from core work." },
    ],
  },
  {
    slug: "svc-mobile",
    title: "Mobile App Development",
    tagline: "Native experiences. Cross-platform reach.",
    description: "Full-cycle mobile app development from concept to App Store deployment. React Native, Flutter, and native iOS/Android apps designed for performance, engagement, and monetization.",
    color: "#22c55e",
    gradient: "from-green-500 to-emerald-600",
    iconName: "smartphone",
    features: [
      { title: "Cross-Platform Engineering", desc: "React Native and Flutter apps with near-native performance, shared codebases, and platform-optimized UX." },
      { title: "Native iOS & Android", desc: "Swift and Kotlin development for apps requiring deep platform integration, ARKit, or hardware-level access." },
      { title: "UI/UX for Mobile", desc: "Mobile-first interaction design with gesture-based navigation, haptic feedback, and platform-specific design patterns." },
      { title: "App Store Optimization", desc: "ASO strategies including keyword research, preview videos, A/B tested screenshots, and review management." },
      { title: "Analytics & Crash Reporting", desc: "Real-time user analytics, crash reporting with stack traces, and performance monitoring for every release." },
    ],
    stats: [
      { label: "Apps Published", value: "95+" },
      { label: "Total Downloads", value: "4.8M+" },
      { label: "Avg. App Rating", value: "4.7" },
      { label: "Retention (D30)", value: "34%" },
    ],
    testimonials: [
      { name: "Hannah Brooks", role: "CEO, Pulse Fitness", text: "Our React Native app launched on both platforms simultaneously. Users praise the smooth performance and intuitive design." },
      { name: "Viktor Sorokin", role: "Product Manager, RideOn", text: "They delivered a complex ride-hailing app with real-time tracking, payments, and chat — on time and on budget." },
    ],
  },
  {
    slug: "svc-api",
    title: "API & Integration Development",
    tagline: "Connect everything. Automate anything.",
    description: "Custom API development and third-party integration services that connect your systems, automate data flow, and unlock new capabilities. REST, GraphQL, webhooks, and event-driven architecture.",
    color: "#f43f5e",
    gradient: "from-rose-500 to-red-600",
    iconName: "plug",
    features: [
      { title: "REST & GraphQL APIs", desc: "Versioned, documented, and tested APIs with rate limiting, authentication, and comprehensive OpenAPI/Swagger specs." },
      { title: "Third-Party Integrations", desc: "Pre-built connectors and custom integrations for Stripe, Slack, Salesforce, HubSpot, Shopify, and 100+ other platforms." },
      { title: "Webhook & Event Systems", desc: "Event-driven architectures with webhook delivery, retry logic, and dead-letter queues for reliable asynchronous processing." },
      { title: "API Gateway & Management", desc: "Centralized gateway with authentication, rate limiting, caching, monitoring, and developer portal for API consumers." },
      { title: "Migration & Legacy Integration", desc: "Strategies for connecting modern systems with legacy databases, mainframes, and SOAP endpoints without disruption." },
    ],
    stats: [
      { label: "APIs Built", value: "220+" },
      { label: "Integrations Active", value: "430+" },
      { label: "Avg. Uptime", value: "99.99%" },
      { label: "Docs Generated", value: "1.6K+" },
    ],
    testimonials: [
      { name: "Priya Singh", role: "CTO, DataFlow", text: "They built a unified API layer that connects 12 internal systems. Our integration development speed increased 5x." },
      { name: "Alex Wallace", role: "Engineering VP, ConnectHealth", text: "The HL7 FHIR API they built for us passed certification on the first attempt. Deep healthcare domain knowledge." },
    ],
  },
]
